server:
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: dev
  cache:
    type: redis
  data:
    web:
      pageable:
        max-page-size: 100
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate

app:
  cards:
    max-per-user: 5
  cache:
    default-ttl: 1h
    cache-ttls:
      users: 7d
      users_pages: 15m
      internal_users: 7d
      cards: 15m
      cards_pages: 15m
      cards_user: 15m

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
